return {
  'akinsho/toggleterm.nvim',
  version = "*",
  cmd = { 'ToggleTerm' },
  keys = {
    { "<C-\\>" },
    { "<leader>ta", "<cmd>1ToggleTerm size=80<cr>", desc = "Terminal 1" },
    { "<leader>tb", "<cmd>2ToggleTerm size=80<cr>", desc = "Terminal 2" },
    { "<leader>tc", "<cmd>3ToggleTerm size=80<cr>", desc = "Terminal 3" },
    { "<leader>tf", "<cmd>ToggleTerm direction=float<cr>", desc = "Float" },
    { "<leader>th", "<cmd>ToggleTerm size=10 direction=horizontal<cr>", desc = "Horizontal" },
    { "<leader>tv", "<cmd>ToggleTerm size=80 direction=vertical<cr>", desc = "Vertical" },
  },
  opts = {
    size = 20,
    open_mapping = [[<C-\>]],
    hide_numbers = true,
    shade_filetypes = {},
    shade_terminals = true,
    shading_factor = 2,
    start_in_insert = true,
    insert_mappings = true,
    persist_size = true,
    direction = "float",
    close_on_exit = true,
    shell = vim.o.shell,
    float_opts = {
      border = "curved",
      winblend = 0,
      highlights = {
        border = "Normal",
        background = "Normal",
      },
    },
  },
}
